### ISSUE TITLE
Nav breaking out of browser 

### ISSUE THREAD

**Issue by char1129** [PoioZyem/confectionery-website-prototype#2]
See attached photo.

Maybe restraining the div around the nav or the nav itself may he’ll by defining the width: 100%; or taking out any margins the a tags have.

![278E91E7-57DE-4A5F-9ED3-8E5A7473BD43](https://user-images.githubusercontent.com/55107755/70467177-b4dab180-1a92-11ea-957b-2f18af331d31.png)

**Comment by VanshitaGandhi** [comment]
Hi, I'm testing the website in Opera mini on an Iphone. 
The navigation bar doesn't display properly and there are some spelling mistakes in the content. (example: Definition, Techniques, etc)

**Comment by PoioZyem** [comment]
It should be work by now~
